// frontend-client/Slider.vue
<template>
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    
    <div class="carousel-item active">
      <img :src="images[0].image" class="d-block w-100" :alt="images[0].id">
    </div>
    
    <div class="carousel-item">
      <img :src="images[1].image" class="d-block w-100" :alt="images[1].id">
    </div>
    
    <div class="carousel-item">
      <img :src="images[2].image" class="d-block w-100" :alt="images[2].id">
    </div>
  
    </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</template>

<script>
// Aquí va el código Javascript
</script>

<style>

</style>

// react-client/src/components/Slider.jsx
import { useState, useEffect } from 'react'

const slides = {
    imagesMobile: [
        { id: 1, image: 'https://d13lnhwm7sh4hi.cloudfront.net/wp-content/uploads/2021/01/08140919/banner2tarjetaefectivo767X767.png', description: "Image One" },
        { id: 2, image: 'https://d13lnhwm7sh4hi.cloudfront.net/wp-content/uploads/2021/01/08141942/banner1tarjetaefectivo767X767.png', description: "Image Two" },
        { id: 3, image: 'https://d13lnhwm7sh4hi.cloudfront.net/wp-content/uploads/2021/01/08142916/banner3tarjetaefectivo767X767.png', description: "Image Three" }
    ],
    imagesDesktop: [
        { id: 1, image: 'https://d13lnhwm7sh4hi.cloudfront.net/wp-content/uploads/2021/01/08143805/banner4tarjetaefectivo1400x412.png', description: "Image One" },
        { id: 2, image: 'https://d13lnhwm7sh4hi.cloudfront.net/wp-content/uploads/2021/01/08141759/banner1tarjetaefectivo1400x412.png', description: "Image Two" },
        { id: 3, image: 'https://d13lnhwm7sh4hi.cloudfront.net/wp-content/uploads/2021/01/08140558/banner2tarjetaefectivo1400x412.png', description: "Image Three" }
    ]
}

const Slider = () => {

    const [device, setDevice] = useState('')

    useEffect(() => {
        setDevice(window.screen.width)
    }, [])

    return (
        <div className="">
            <div id="carouselExampleControls" className="carousel slide" data-bs-ride="carousel">

                {
                    device >= 600 ?

                        <div className="carousel-inner">

                            {
                                slides.imagesDesktop.map(slide => {
                                    return (
                                        <div class={slide.id == 1 ? "carousel-item active" : "carousel-item"}>
                                            <img src={slide.image} className="d-block w-100" alt={slide.id} />
                                        </div>
                                    )
                                })
                            }



                        </div>
                        :
                        <div className="carousel-inner">

                            {
                                slides.imagesMobile.map(slide => {
                                    return (
                                        <div class={slide.id == 1 ? "carousel-item active" : "carousel-item"}>
                                            <img src={slide.image} className="d-block w-100" alt={slide.id} />
                                        </div>
                                    )
                                })
                            }

                        </div>
                }



                <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span className="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span className="visually-hidden">Anterior</span>
                </button>

                <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span className="carousel-control-next-icon" aria-hidden="true"></span>
                    <span className="visually-hidden">Siguiente</span>
                </button>

            </div>
        </div>
    )
}

export default Slider
